name = "cloudflare-file-hosting"
main = "worker.js"
compatibility_date = "2025-03-21"

[site]
bucket = "./public"

[[kv_namespaces]]
binding = "STATIC_CONTENT_KV"  # New binding name
id = "0f5b1e647f2a473ca6d3e2a1d1b9b409"  # Replace with your actual KV namespace ID

[env.production]
logpush = true

[observability.logs]
enabled = true

[vars]
GOOGLE_DRIVE_API_KEY = "your-google-drive-api-key-here"
GOOGLE_DRIVE_ACCESS_TOKEN = "your-google-drive-access-token-here"
GOOGLE_DRIVE_FOLDER_ID = "your-google-drive-folder-id-here"
BOT_TOKEN = "your-bot-token-here"
