name = "cloudflare-file-hosting"
main = "worker.js"
compatibility_date = "2025-03-21"

[site]
bucket = "./public"

[[kv_namespaces]]
binding = "STATIC_CONTENT_KV"  # New binding name
id = "0f5b1e647f2a473ca6d3e2a1d1b9b409"  # Replace with your actual KV namespace ID

[env.production]
logpush = true

[observability.logs]
enabled = true

[vars]
GOOGLE_DRIVE_API_KEY = "AIzaSyBVzpotSqBLeRQQR2AokBjLfimfXUjGj4w"
GOOGLE_DRIVE_ACCESS_TOKEN = "ya29.c.c0ASRK0Ga8kbB9BCZgHEs20Jloq7g_xfS9VFM_JoUKqSwmz8PSFkXHMwpQvlVoRzY0dg902OIcOamgjWq13-w8EHjH14l_qX0yhX6gG3RB-70SUTquryk5hCJpvBfVnoURG-nw-K-eT6s_fJ7GK67HVB4D9gphpHl5E0fzGMFwO0krQY98xx6WzQlkeyXSu7J4aFJYANGyhP-UDwk36N0t1DtN5fpve1pgyHQ-_cv9mKuime-f5Pk9ndx_1056O2ocqmmVh3cmQ-pTQsA1U149VhVueP-Kuo3h-qfnYt6lPwaKwciGPj8w58UvUGa2nnCEDyH32__qrZzAn6vmq47FffeazMNH4E3EBBjupr63loCaw0fCqLRaAgE383Pswe9F8QVfymjOhIvzX9RshORcphyrboJssJaqIzp1b8_oXvRkWm8UWsVSQ_4BQqJW2t7id7oIU39hrYh3s_ivp04vzklQ8Y4au3vSYUB00yV6UR9wg2scb_2I403ribpUcq2t8dak9m7bRjay0Iqm3noy-9MbryJiXzabp7wZyfew_nWpl_m5JncatpMmZgZ0IYz96aXo6MxrB-UokmxitRpdRm3Ie0-1k2_WOB1ffg8MS-QgY_h07IfjwqZc07Ym7-bmFmeJQs75RirZ0-iOjghMVnMizyk200h5fu1SxMv3-aRojakwZUuYlRy-nugzScjxb3Veu7FtXdWalmpu8g6y1tJ_XiQhti7iueeMMiyVYhMX6Bgif8Ycyka5xp6o2idWbd9__iWWq-o1I8Z6-gb25uogpgUar1zBwdiu56W862F77koakjnBcUI4-fv0S644yVQQ2nQ5q6qyRvZU2ab-lJZx0_eyJgn4eyh9tlw24tm4OzrUvosk_22pzc1Me7-k-8hJsWY9OQ2zUahOuUwuhz621kwcXdnM-jeyS47zWYhIZb5W9U0WZ_sFZSuOIrhSjOX3akW9Oxg_1n_XaUJYl4VxQ8ydjS0cVUJ5Mlghj1tgyccZShlfcIw"
GOOGLE_DRIVE_FOLDER_ID = "1gYJTWj1qPO68t5biLu1zoP60NhbhdrWN"
BOT_TOKEN = "11"
